# Generated by Django 6.0.3 on 2026-04-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
